_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "6": 4.33.1
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
optimizer:
    value: adam
optimizer_configs:
    value:
        adam:
            name: Adam
            weight_decay: 0.01
        sgd:
            momentum: 0.9
            name: SGD
trainer:
    value:
        batch_size: 64
        beta1: 0.0001
        beta2: 0.02
        device: cuda:7
        flip_augment: false
        hid_size: 128
        num_epochs: 100
        num_timesteps: 1000
        num_workers: 4
        peak_lr: 0.0001
