_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "6": 4.33.1
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 128
betas:
    value:
        - 0.0001
        - 0.02
hidden_size:
    value: 128
learning_rate:
    value: 1e-05
num_epochs:
    value: 3
num_timesteps:
    value: 1000
